name: Dev-deploy

on:
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      # Build project
      - name: Build project
        run: npm run build

      # Upload production-ready build files
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

      # Login to docker hub
      - name: Login to docker hub
        run: docker login -u ${{ env.DOCKER_USERNAME }} -p ${{ env.DOCKER_PASSWORD }}

      # Build Docker Image
      - name: Build Docker Image
        run: docker build -t ${{ env.DOCKER_USERNAME }}/mern-todos-app-frontend:latest  .

      # Publish Image to docker hub
      - name: Publish Image to docker hub
        run: docker push ${{ env.DOCKER_USERNAME }}/mern-todos-app-frontend:latest
